sudo: 'required'
language: node_js
cache: yarn
services: docker
node_js: '10'
script:
  - cd packages/golang
  - bash compile.sh
  - cp -a ./bin/. ../node/dist/bin/
  - cp -a ./bin/. ../nginx/bin/
  - cd ../node
  - cp ../../README.md ./
  - yarn install
  - yarn build
  - cd ../nginx
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker build -t beamaustralia/react-env:$TRAVIS_TAG -t beamaustralia/react-env:latest .  
  - ../../
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    tags: true    
  