sudo: 'required'
language: node_js
cache: yarn
services: docker
node_js: '10'
script:
  - cd packages/golang
  - bash compile.sh
  - cp -a ./bin/. ../node/dist/bin/
  - cp -a ./bin/. ../nginx/bin/
  - cd ../node
  - yarn install
  - yarn build
  - cd ../nginx
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker build -t beamaustralia/react-env:$TRAVIS_TAG -t beamaustralia/react-env:latest .  
after_success:
  - docker push beamaustralia/create-react:$TRAVIS_TAG
  - docker push beamaustralia/create-react:latest 
  - cd ../node
  - npm install -g npm-cli-login
  - npm-cli-login
  - npm publish --access public ---tag $TRAVIS_TAG
