sudo: 'required'
language: node_js
cache: yarn
services: docker
node_js: '10'

### Build
script:
  # build go binaries
  - cd packages/golang
  - bash compile.sh
  - cp -a ./bin/. ../node/dist/bin/
  - cp -a ./bin/. ../nginx/bin/
  # build node package
  - cd ../node
  - cp ../../README.md ./
  - yarn install
  - yarn build
  - cd ../../

## Publish
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    tags: true    
  