sudo: 'required'

services:
  - docker

script:
  - docker build -t beamaustralia/create-react-env .

deploy:
  provider: script
  script: bash scripts/push.sh
  on:
    tags: true
    all_branches: true
    